site_name: RTP Competency Framework
site_description: Competency Framework for Research Technical Professionals working with Secure Data Environments
site_author: EPSRC SkillsHub Team
repo_url: https://github.com/UoM-Data-Science-Platforms/sde-skills

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.expand
    - navigation.instant
    - navigation.search.highlight
    - navigation.search.shareable
    - navigation.search.suggest
    - navigation.search.suggest.external
    - navigation.search.suggest.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.shareable
    - search.suggest
    - search.suggest.external
    - search.suggest.indexes
  nav:
    - Home: index.md
    - Skills Matrix:
        - Overview: skills_matrix/overview.md
        - Software Development & Testing: skills_matrix/software_development_testing.md
        - Data Management & Engineering: skills_matrix/data_management_engineering.md
        - Architecture & Design: skills_matrix/architecture_design.md
        - Cloud Infrastructure: skills_matrix/cloud_infrastructure.md
        - Security & Compliance: skills_matrix/security_compliance.md
        - Service Management: skills_matrix/service_management.md
        - Technical Collaboration & Documentation: skills_matrix/technical_collaboration_documentation.md
        - Project & Process Management: skills_matrix/project_process_management.md
        - Costing & Financial Oversight: skills_matrix/costing_financial_oversight.md
    - Contributing: contributing.md
    - About: about.md
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
