nav:
  - index.md
  - Skills Matrix:
      - skills_matrix/_overview.md
      - skills_matrix/software_development_testing.md
      - skills_matrix/data_management_engineering.md
      - skills_matrix/architecture_design.md
      - skills_matrix/cloud_infrastructure.md
      - skills_matrix/security_compliance.md
      - skills_matrix/service_management.md
      - skills_matrix/technical_collaboration_documentation.md
      - skills_matrix/project_process_management.md
      - skills_matrix/costing_financial_oversight.md
  - about.md
  - contributing.md
