nav:
  - Welcome: index.md
  - Skills Matrix:
      - skills_matrix/_overview.md
      - skills_matrix/software_development_testing.md
      - skills_matrix/data_management_engineering.md
      - skills_matrix/architecture_design.md
      - skills_matrix/cloud_infrastructure.md
      - skills_matrix/security_compliance.md
      - skills_matrix/service_management.md
      - skills_matrix/technical_collaboration_documentation.md
      - skills_matrix/project_process_management.md
      - skills_matrix/costing_financial_oversight.md
  - Competency Framework:
      - competency_framework/framework_mapping.md
      - competency_framework/overview.md
      - competency_framework/safe_access_identity.md
      - competency_framework/safe_data_management.md
      - competency_framework/safe_governance_compliance.md
      - competency_framework/safe_outputs_disclosure_control.md
      - competency_framework/safe_projects_operations.md
      - competency_framework/safe_technology_engineering.md
  - The Team: about.md
  - Contribute: contributing.md
